ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PARTIAL_CANCELED'; -- 이미 존재 시 no-op
DO $$ BEGIN CREATE TYPE "PaxType" AS ENUM ('ADULT','CHILD','INFANT'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "RefundKind" AS ENUM ('FULL_CANCEL','TRAVELER_CANCEL','DISCRETIONARY'); EXCEPTION WHEN duplicate_object THEN null; END $$;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "refundedAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RefundJob" ADD COLUMN IF NOT EXISTS "kind" "RefundKind" NOT NULL DEFAULT 'FULL_CANCEL';
ALTER TABLE "RefundJob" ADD COLUMN IF NOT EXISTS "baseAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RefundJob" ADD COLUMN IF NOT EXISTS "seatsReleased" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RefundJob" ADD COLUMN IF NOT EXISTS "idempotencyKey" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "RefundJob_idempotencyKey_key" ON "RefundJob"("idempotencyKey");
ALTER TABLE "Traveler" ADD COLUMN IF NOT EXISTS "paxType" "PaxType";
ALTER TABLE "Traveler" ADD COLUMN IF NOT EXISTS "unitPrice" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Traveler" ADD COLUMN IF NOT EXISTS "canceledAt" TIMESTAMP(3);
ALTER TABLE "Traveler" ADD COLUMN IF NOT EXISTS "canceledByRefundJobId" TEXT;
